dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu       CPP=1 DYLIB=1 STD=1 OPENSSL=0.5.5  RUN=1
    - env: TARGET=arm-unknown-linux-gnueabi       CPP=1 DYLIB=1 STD=1 OPENSSL=0.5.5  RUN=1
    - env: TARGET=arm-unknown-linux-musleabi                    STD=1                RUN=1
    - env: TARGET=armv7-unknown-linux-gnueabihf   CPP=1 DYLIB=1 STD=1 OPENSSL=0.5.5  RUN=1
    - env: TARGET=armv7-unknown-linux-musleabihf                STD=1                RUN=1
    - env: TARGET=i686-unknown-linux-gnu          CPP=1 DYLIB=1 STD=1 OPENSSL=0.5.5  RUN=1
    - env: TARGET=i686-unknown-linux-musl                       STD=1                RUN=1
    - env: TARGET=mips-unknown-linux-gnu          CPP=1 DYLIB=1 STD=1 OPENSSL=0.5.5  RUN=1
    - env: TARGET=mips64-unknown-linux-gnuabi64   CPP=1 DYLIB=1 STD=1 OPENSSL=0.7.17 RUN=1
    - env: TARGET=mips64el-unknown-linux-gnuabi64 CPP=1 DYLIB=1 STD=1 OPENSSL=0.7.17 RUN=1
    - env: TARGET=mipsel-unknown-linux-gnu        CPP=1 DYLIB=1 STD=1 OPENSSL=0.5.5  RUN=1
    - env: TARGET=powerpc-unknown-linux-gnu       CPP=1 DYLIB=1 STD=1 OPENSSL=0.5.5  RUN=1
    - env: TARGET=powerpc64-unknown-linux-gnu     CPP=1 DYLIB=1 STD=1 OPENSSL=0.7.17 RUN=1
    - env: TARGET=powerpc64le-unknown-linux-gnu   CPP=1 DYLIB=1 STD=1 OPENSSL=0.7.17 RUN=1
    - env: TARGET=s390x-unknown-linux-gnu         CPP=1 DYLIB=1 STD=1 OPENSSL=0.7.17
    - env: TARGET=sparc64-unknown-linux-gnu       CPP=1 DYLIB=1       OPENSSL=0.5.5  RUN=1
    - env: TARGET=x86_64-unknown-linux-musl                     STD=1 OPENSSL=0.5.5  RUN=1 DEPLOY=1

    # OSX
    - env: TARGET=i686-apple-darwin                     DYLIB=1 STD=1                RUN=1
      os: osx
    - env: TARGET=x86_64-apple-darwin                   DYLIB=1 STD=1                RUN=1 DEPLOY=1
      os: osx

    # BSD
    - env: TARGET=i686-unknown-freebsd                  DYLIB=1 STD=1 OPENSSL=0.7.17
    - env: TARGET=x86_64-unknown-dragonfly              DYLIB=1       OPENSSL=0.5.5
    - env: TARGET=x86_64-unknown-freebsd                DYLIB=1 STD=1 OPENSSL=0.5.5
    - env: TARGET=x86_64-unknown-netbsd                 DYLIB=1 STD=1 OPENSSL=0.7.17

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu           CPP=1 DYLIB=1 STD=1

    # Bare metal
    - env: TARGET=thumbv6m-none-eabi                                                 RUN=1
    - env: TARGET=thumbv7em-none-eabi                                                RUN=1
    - env: TARGET=thumbv7em-none-eabihf                                              RUN=1
    - env: TARGET=thumbv7m-none-eabi                                                 RUN=1
env:       TARGET=x86_64-unknown-linux-gnu        CPP=1 DYLIB=1       OPENSSL=0.5.5  RUN=1 DEPLOY=1

install:
  - curl https://sh.rustup.rs -sSf |
    sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env
  - test $TRAVIS_OS_NAME = osx ||
      which cargo clone ||
      cargo install cargo-clone --vers 0.1.0

script:
  - bash ci/script.sh

after_success:
  - sh ci/after_success.sh

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - master
    - try

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "tf3b2Um1hbLwvzZBok9wOrRSoshM3dwUmuZ9lkq79FtFvShmNWDR8zcgJK2/NoCwK7XJiOM+PP0F+NRdxv8KjwJnS3GzP38ZSiGmwRteyA8F2vO/FymJBntCi64VQqs+CxfCCCl0NAANfAP0PUabO9Df70QDVxPJmJoyB1d2XE+AuNeYS0Yz3s/lBWkXmwrgQCVLXhapLZLjXYbn7liaDOLWqpogWmwlIFvw4UMtHjj8/IBG53rz+Yyq7MZnag+P8TDhNgmL/Btr8eZfdInzkWj+6aII8q2S44CigvBWwjcHGRSdDcHSRfv4fQ8nyIY4Qq4aewB06clMQ6mkJjGupqTeD6VmVj9mavhcJyorzctpskt8K8EoNDUUUH7YIhi4SgxoT4Uie4HQTVH449gULai6uAD4lLmFlQWPGqFbkm1oNS+B8VsQtsyrY9HsTO5WDh6OGa/74bAVX6FogjPcD3sJIcguuVNEUmgbErkGSoGVhC1bC+KPlplby8Ogn/bKKePEB9bYx6ZGhbeYr992iaWM52oOujnUF/shQ+VScjPKy3p0HjbuIlyua0NSQ0MOlvFzM/hKTKL9TH56mOtFi0Gn+AuuHPTmy6r3ZnueSlPeMm55lRhjWWxXJqkqLQRFFMBcfmuaOC/07tVOcvEpFyAzYWgfdGD4WemaV0alPn8="
  file_glob: true
  file: cross-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    condition: $DEPLOY = 1
    tags: true

before_cache:
  - test $TRAVIS_OS_NAME = osx ||
    docker history -q japaric/$TARGET:latest |
    grep -v \<missing\> |
    xargs docker save |
    gzip > $HOME/docker/$TARGET.tar.gz

cache:
  directories:
    - $HOME/docker

# restore the cache
before_install:
  - test $TRAVIS_OS_NAME = osx ||
    zcat $HOME/docker/$TARGET.tar.gz | docker load || true

notifications:
  email:
    on_success: never
